name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      RAINDROP_TOKEN: ci
      UPSTASH_REDIS_REST_TOKEN: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--no-frozen-lockfile]
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm exec turbo build
      - run: pnpm exec turbo test
